version: '3.8'

services:
  traefik:
    image: traefik:v2.8
    command:
      - "--api.insecure=true"                  # Enable the Traefik dashboard
      - "--providers.docker=true"              # Enable Docker provider
      - "--entrypoints.web.address=:80"        # Define the entrypoint for HTTP
      - "--entrypoints.websecure.address=:443" # Define the entrypoint for HTTPS (if needed)
    ports:
      - "80:80"                                # Expose HTTP port
      - "443:443"                              # Expose HTTPS port
      - "8080:8080"                            # Expose Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Allow Traefik to access Docker socket

  nginx1:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Host(`domain1.com`)"
      - "traefik.http.routers.nginx1.entrypoints=web"  # Use the "web" entrypoint (port 80)
      - "traefik.http.services.nginx1.loadbalancer.server.port=80" # Nginx is listening on port 80 internally
    ports:
      - "81:80"  # Expose container's port 80 on host port 81

  nginx2:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`domain2.com`)"
      - "traefik.http.routers.nginx2.entrypoints=web"  # Use the "web" entrypoint (port 80)
      - "traefik.http.services.nginx2.loadbalancer.server.port=80" # Nginx is listening on port 80 internally
    ports:
      - "82:80"  # Expose container's port 80 on host port 82

networks:
  default:
    external:
      name: traefik
